# Ignore this file if not building for Nintendo Switch
if (NOT NintendoSwitch)
    return()
endif()

find_path(SDL2_IMAGE_SWITCH_PATH NAMES SDL2_image.h PATHS /opt/devkitpro/portlibs/switch/include/SDL2)
if (SDL2_IMAGE_SWITCH_PATH)
    set(SDL2_IMAGE_INCLUDE_DIRS ${SDL2_IMAGE_SWITCH_PATH})
    set(SDL2_IMAGE_LIBRARIES /opt/devkitpro/portlibs/switch/lib/libSDL2_image.a)
    set(SDL2_IMAGE_FOUND TRUE)
else()
    set(SDL2_IMAGE_FOUND FALSE)
endif()
mark_as_advanced(SDL2_IMAGE_INCLUDE_DIRS SDL2_IMAGE_LIBRARIES)
if (SDL2_IMAGE_FOUND)
    message(STATUS "Found SDL2_image for Nintendo Switch")
else()
    message(FATAL_ERROR "Could not find SDL2_image for Nintendo Switch. Please install the switch portlibs via devkitpro.")
endif()
include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(SDL2_image DEFAULT_MSG SDL2_IMAGE_LIBRARIES SDL2_IMAGE_INCLUDE_DIRS)
if (SDL2_IMAGE_FOUND)
    set(SDL2_IMAGE_LIBRARIES ${SDL2_IMAGE_LIBRARIES} PARENT_SCOPE)
    set(SDL2_IMAGE_INCLUDE_DIRS ${SDL2_IMAGE_INCLUDE_DIRS} PARENT_SCOPE)
endif()
